name: skript-citizens
author: nylhus
contributor: Equipable
description: Use Citizens api with Skript
version: @version@
api-version: '1.18'
main: ca.nylhus.skriptcitizens.SkriptCitizens
depend: [Skript, Citizens]
website: https://github.com/EquipableMC/skript-citizens